services:

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase
    command: update --changelog-file=changelog.xml --username=credit_user --password=credit_pass --url=jdbc:postgresql://credit_user_db:5432/credit_user_db
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
    networks:
      - credit_network

networks:
  credit_network:
    external: true
